name: Workflow Demo

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt

  download:
    name: download
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: download hello.txt
      uses: actions/download-artifact@v2
      with:
        name: hello-artifact
        path: artifacts
    - name: cat hello.txt
      run: cat ./artifacts/hello.txt 